name: 'tauri-build'
description: 'Build tauri binaries for MacOS, Windows and Linux'
icon: 'box'
color: 'blue'
author: 'Tauri Programme within The Commons Conservancy'
inputs:
  runner:
    description: 'Binary to use to build the application'
  args:
    description: 'Additional arguments for the build command'
  projectPath:
    description: 'Path to the root of the project'
  configPath:
    description: 'Path to the tauri.conf.json file if you want a configuration different from the default one'
  target:
    description: 'The target triple to build against'
  debug:
    description: 'Builds with the debug flag'
    default: false
outputs:
  artifacts:
    description: 'JSON array of artifact paths produced by the build command'
runs:
  using: 'node18'
  main: 'dist/index.js'
