name: 'tauri-action'
description: 'Build tauri binaries for MacOS, Windows and Linux'
author: 'Tauri Programme within The Commons Conservancy'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  releaseId:
    description: 'The id of the release to upload artifacts as release assets'
  tagName:
    description: 'The tag name of the release to create or upload to'
  releaseName:
    description: 'The name of the release to create'
  releaseBody:
    description: 'The body of the release to create'
  releaseDraft:
    description: 'Whether the release to create is a draft or not'
    default: 'false'
  prerelease:
    description: 'Whether the release to create is a prerelease or not'
    default: 'false'
  releaseCommitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
  projectPath:
    description: 'Path to the root of the project that will be built. It must NOT be gitignored.'
    default: '.'
  uploadUpdaterJson:
    description: 'Whether to upload a static JSON file for the updater using GitHub Releases as the CDN'
    default: 'true'
  updaterJsonPreferNsis:
    description: 'Whether the action will use the NSIS (setup.exe) or WiX (.msi) bundles for the updater JSON if both types exist. Will default to false. May default to true for apps using tauri@v2 in the future.'
    default: 'false'
  tauriScript:
    description: 'The script to run to build the Tauri app'
  args:
    description: 'Arguments for the `tauri build` command'
  retryAttempts:
    description: 'The number of times to re-try building the app if the initial build fails or uploading assets if the upload fails.'
  owner:
    description: 'The account owner of the repository'
  repo:
    description: 'The name of the repository'
  githubBaseUrl:
    description: 'The base URL of the GitHub API to use. This is useful if you want to use a self-hosted GitHub instance or a GitHub Enterprise server.'
  releaseAssetNamePattern:
    description: 'The naming pattern to use for the uploaded assets'
  uploadPlainBinary:
    description: 'Whether to upload the plain executable file to the GitHub Releases'
    default: 'false'
  uploadWorkflowArtifacts:
    description: 'Whether to upload the bundles and executables as workflow artifacts. Independent from the release configs. Affected by `uploadPlainBinary`.'
    default: 'false'
  workflowArtifactNamePattern:
    description: 'The naming pattern to use for uploaded workflow artifacts. Ignored if `uploadWorkflowArtifacts` is not enabled.'
  uploadUpdaterSignatures:
    description: 'Whether to upload the .sig files generated by the Tauri CLI. Does not affect the latest.json generator.'
    default: 'true'
  generateReleaseNotes:
    description: "Whether to use GitHub's Release Notes API to generate the release title and body. If `releaseName` is set, it will overwrite the generated title. If `releaseBody` is set, it will be pre-pended to the automatically generated notes. This action is not responsible for the generated content."
    default: 'false'
  mobile:
    description: 'EXPERIMENTAL - Whether to build for mobile or desktop. Can be "android" or "ios" or unset for desktop builds.'
outputs:
  releaseId:
    description: 'The ID of the created release'
  releaseHtmlUrl:
    description: 'The URL users can navigate to in order to view the created release'
  releaseUploadUrl:
    description: 'The URL for uploading assets to the created release'
  artifactPaths:
    description: 'The paths of the generated artifacts'
  appVersion:
    description: 'The version of the app'
runs:
  using: 'node24'
  main: 'dist/index.js'
