name: 'real world tests'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  v2:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--verbose --target universal-apple-darwin --debug'
          - platform: 'ubuntu-22.04'
            args: '--verbose --debug'
          - platform: 'windows-latest'
            args: '--verbose --debug'
          - platform: 'ubuntu-24.04-arm'
            args: '--verbose --debug'
          - platform: 'windows-11-arm'
            args: '--verbose --debug'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # node
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.x.x

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install example dependencies
        run: |
          echo "skipped"
        # disabled to test cli fallback install
        #cd ./.github/fixtures/example-with-tauri-v2
        # pnpm install

      # rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./.github/fixtures/example-with-tauri-v2/src-tauri -> ../../target

      # system
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' || matrix.platform == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev

      - name: Preconfigured Tauri Project
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_SIGNING_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./.github/fixtures/example-with-tauri-v2
          tagName: ${{ !github.event.pull_request.head.repo.fork && 'example-with-tauri-v__VERSION__' || '' }}
          releaseName: 'Release example with preconfigured Tauri app v__VERSION__ for tauri-v2'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.args }}
          updaterJsonKeepUniversal: true
          retryAttempts: 1
          uploadPlainBinary: true
      # assetNamePattern: '[name]x[version]x[platform]x[arch]x[mode]x[setup]x[ext]'
